os: osx
scala:
- 2.11.8
before_install:
- brew update
- brew unlink node
- brew unlink npm
- brew install node
- brew install npm && npm install -g gulp-cli
- brew cask install java
- brew install scala
- brew install sbt
script:
- cd ./backend && sbt test
- cd ../frontend && npm install && gulp test
